### ISSUE TITLE
After World Update 3, starting the game with JumpStarter freezes the game

### ISSUE THREAD

**Issue by wreyniers** [AmbitiousPilots/FSJumpStarter2020#2]
The game seems to load fine, but once in the main menu it keeps acting like the space bar is being hit (in the map moad the Load/Save map dialog appears and reappears persistently). Eventually the game freezes and I have to kill it through task manager. The default launch shortcut from Steam works perfectly, albeit with the loader videos/screens.

Thanks!

**Comment by MatchstickUK** [comment]
I was going mad trying to work out what was causing that so thanks for working it out and creating this issue

**Comment by AmbitiousPilots** [comment]
I released version 2 of FSJumpStarter2020. This is now fixed. Thanks for reporting ;-)
