### ISSUE TITLE
[Request] Disable always on top

### ISSUE THREAD

**Issue by Jackaroo05** [AmbitiousPilots/FSJumpStarter2020#3]
The splash screen takes up a decent portion of the screen and is always on top of the screen, making people with one monitor unable to see other apps until it goes away. It gets really annoying, and therefore I would like for the splash screen to not be always on top.

**Comment by AmbitiousPilots** [comment]
Thank you for the feedback. I'm planning on reworking the splash screen in the future. Stay tuned.

**Comment by Jackaroo05** [comment]
Any updates on this? 3+ months have gone by and this is still very annoying.
